name    = Sort-XS
author  = Nicolas R <atoomic@cpan.org>
license = Perl_5
copyright_holder = Nicolas R
copyright_year   = 2011

[OurPkgVersion]

[MetaJSON]
[MetaConfig]

[MetaProvides::Package]

[NextRelease]
filename = Changes

[Prereqs / RuntimeRequires]
Carp = 0
XSLoader = 0
Exporter = 0

[Prereqs / TestRequires]
Test::More = 0

[Prereqs / ConfigureRequires]
ExtUtils::MakeMaker = 0

[TestRelease]

[@Git]
allow_dirty = Changes
allow_dirty = dist.ini
allow_dirty = README.md
allow_dirty = Makefile.PL

push_to = origin
push_to = origin HEAD:refs/heads/released

[Run::AfterBuild]
run = cp %d/Makefile.PL ./
run = git status --porcelain | grep 'M Makefile.PL' && git commit -m 'Makefile.PL auto-updated by dist.ini' Makefile.PL && echo "# Makefile.PL auto-update" || echo "# Makefile.PL up to date"

[Git::NextVersion]

[@Filter]
-bundle = @Basic
-remove = ExtraTests
-remove = GatherDir
-remove = MakeMaker

[GatherDir]
exclude_filename = Makefile.PL
exclude_filename = CLAUDE.md
exclude_filename = README.md

[MakeMaker::Awesome]
header = use Config;
WriteMakefile_arg = OBJECT => 'sort.o XS.o'
WriteMakefile_arg = DEFINE => ($Config{"byteorder"} =~ /^1234/ ? '-DARCH_IS_BIG_ENDIAN=0' : '') . ($^O =~ /^MSWin/i ? ' -DWINDOWS' : '')

[PruneFiles]
match = ~$
match = \.project$

; -- static meta-information
[MetaResources]
bugtracker.web  = https://github.com/atoomic/Sort-XS/issues
repository.url  = https://github.com/atoomic/Sort-XS.git
repository.web  = https://github.com/atoomic/Sort-XS
repository.type = git

[ReadmeAnyFromPod]
type = gfm
filename = README.md
location = root
