---
abstract: 'Full XS implementation of common crypt() algorithms'
author:
  - 'John Lightsey <jd@cpanel.net>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-Passwd-XS
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.600
